# [build]
#   command = "npm run export"
#   publish = "__sapper__/export"
#   NODE_ENV = "10.18.1"


# [dev]
#   command = "npm run dev"

[[redirects]]
  from = "https://musikversicherung.netlify.app/*"
  to = "https://musikversicherung.com/:splat"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404 